import { getAnthropic, hasAnthropic, MODEL } from "./anthropic";
import { geminiChat, hasGemini } from "./gemini";
import {
  heuristicDetect,
  computeMetrics,
  computeSignals,
  splitSentences,
  verdictFromScore,
  isArabicText,
  type Sentence,
  type StyleMetrics,
  type Engine,
  type Confidence,
  type DetectResult,
} from "./detector-stats";

/* ------------------------------------------------------------------
   Provider selection: Gemini → OpenAI → Anthropic → heuristic.
   Override with AI_PROVIDER=gemini|openai|anthropic when several keys are set.

   Gemini leads because it is the one with a free tier, and a detector that
   only reaches its real accuracy behind a paid key mostly runs at its floor.
   Any of them beats the statistical engine on the case that matters — telling
   careful human prose apart from machine prose that carries no filler.
------------------------------------------------------------------ */
const OPENAI_MODEL = process.env.OPENAI_MODEL || "gpt-4o-mini";

function hasOpenAI(): boolean {
  return Boolean(process.env.OPENAI_API_KEY);
}

type Provider = "gemini" | "openai" | "anthropic" | "heuristic";

function pickProvider(): Provider {
  const pref = process.env.AI_PROVIDER;
  if (pref === "gemini" && hasGemini()) return "gemini";
  if (pref === "openai" && hasOpenAI()) return "openai";
  if (pref === "anthropic" && hasAnthropic()) return "anthropic";
  if (hasGemini()) return "gemini";
  if (hasOpenAI()) return "openai";
  if (hasAnthropic()) return "anthropic";
  return "heuristic";
}

async function openaiChat(
  system: string,
  user: string,
  jsonMode: boolean,
  maxTokens: number
): Promise<string> {
  const res = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: OPENAI_MODEL,
      max_tokens: maxTokens,
      ...(jsonMode ? { response_format: { type: "json_object" } } : {}),
      messages: [
        { role: "system", content: system },
        { role: "user", content: user },
      ],
    }),
  });
  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`openai_error ${res.status}: ${detail.slice(0, 200)}`);
  }
  const json = await res.json();
  return json.choices?.[0]?.message?.content ?? "";
}

export type { Sentence, StyleMetrics, Engine, Confidence, DetectResult };
export { computeMetrics };

/** Cheap deterministic AI-style score, used for the humanize verify loop. */
export function styleSignalScore(text: string): number {
  return heuristicDetect(text).score;
}

export type HumanizeStyle = "natural" | "academic" | "casual";
export type HumanizeResult = {
  text: string;
  engine: Engine;
};

/* ------------------------------------------------------------------
   Claude-powered detector
------------------------------------------------------------------ */
async function claudeDetect(text: string, locale: string): Promise<DetectResult> {
  const anthropic = getAnthropic();
  const metrics = computeMetrics(text);
  const signals = computeSignals(text);
  const msg = await anthropic.messages.create({
    model: MODEL,
    max_tokens: 2000,
    system: DETECT_SYSTEM,
    messages: [{ role: "user", content: detectPrompt(text, locale, metrics, signals) }],
  });
  const raw = msg.content.find((c) => c.type === "text");
  const jsonText = raw && "text" in raw ? raw.text : "{}";
  const { score, sentences } = parseDetectJson(jsonText, text);
  return {
    score,
    verdict: verdictFromScore(score),
    confidence: "medium",
    sentences,
    metrics,
    engine: "claude",
  };
}

/**
 * The model is told what it is for, not just what to output.
 *
 * Left to itself a language model scores this task like a marker: careful,
 * conventional, correctly-punctuated prose reads to it as "AI-like", which
 * means it convicts exactly the people least able to argue back — second
 * language writers, students trained on a rigid rubric, meticulous editors.
 * Those groups are the documented failure mode of every detector on the
 * market and the reason this one publishes a confidence rating at all, so the
 * instruction to discount fluency is not a nicety; it is the product.
 */
const DETECT_SYSTEM = `You are the writing-style analyst behind "Sahihly", an AI-text detector used by students, teachers and editors in Arabic and English.

You estimate how likely a passage was generated by a language model. You are never certain, and you say so through the number rather than through hedging prose.

What actually distinguishes generated text:
- Even rhythm. Generated prose rarely drops below eight words or runs past thirty; human writing punches short and rambles long.
- Hedged, unstaked claims. "generally", "significant", "plays a role", "يُعد", "بشكل كبير" — a writer who knows the specific thing says the specific thing.
- Stock connectives: "furthermore", "in conclusion", "علاوة على ذلك", "في الختام".
- Coverage without commitment: every side balanced, no position a reader could disagree with.
- Absence of the unshareable: a detail only this author would know, a number they checked, an aside that serves nothing.

What does NOT indicate generation, and must not raise your score:
- Correct grammar, careful punctuation, or formal register.
- Writing in a second language. Controlled vocabulary and reliable sentence patterns are what fluency in a second language looks like, and detectors flag it wrongly far more often than they flag it rightly.
- Academic or documentation conventions. A methods section, a literature summary, a policy paragraph is SUPPOSED to be predictable; that is the discipline, not a model.
- Translated prose, which carries the source language's structure and reads unusually even.
- Subject matter you find dull.

Score honestly, including at the low end. Most text people paste was written by a person.

Respond with ONLY valid JSON.`;

function detectPrompt(
  text: string,
  locale: string,
  metrics: StyleMetrics,
  signals: ReturnType<typeof computeSignals>
): string {
  const pct = (x: number) => Math.round(x * 100);
  return `Analyze the following text (language: ${locale}).

Independent statistical measurements of this exact passage. Each is already
calibrated against normal human writing in its own language, so 0 means
"indistinguishable from ordinary human prose in this language" and 100 means
"as far from it as this measure goes". Weigh these alongside your own reading;
where you disagree with them, trust your reading and the disagreement will be
reported to the user as lower confidence.

- flat sentence rhythm: ${pct(signals.uniformity)}/100
- never leaves the 8-30 word band: ${pct(signals.bandLock)}/100
- hedge and booster density: ${pct(signals.hedging)}/100
- stock connective density: ${pct(signals.stock)}/100
- enumerated advice in prose: ${pct(signals.enumeration)}/100
- raw average sentence length: ${metrics.avgSentenceLen} words
- sentences measured: ${splitSentences(text).length}

If fewer than about eight sentences were measured, those shape-based numbers
are noise and you should rely on your reading of the wording instead.

Return JSON:
{"score": <int 0-100 probability AI-generated>, "sentences": [{"text": "<sentence>", "score": <int 0-100>}]}
Split the passage into its sentences and score each. Keep sentence text verbatim.

TEXT:
"""${text}"""`;
}

function parseDetectJson(raw: string, text: string): { score: number; sentences: Sentence[] } {
  const parsed = JSON.parse(raw.replace(/```json|```/g, "").trim());
  const score = Math.min(100, Math.max(0, Math.round(parsed.score ?? 50)));
  const sentences: Sentence[] = Array.isArray(parsed.sentences)
    ? parsed.sentences.map((s: { text: string; score: number }) => ({
        text: String(s.text),
        score: Math.min(100, Math.max(0, Math.round(s.score ?? score))),
      }))
    : splitSentences(text).map((t) => ({ text: t, score }));
  return { score, sentences };
}

async function openaiDetect(text: string, locale: string): Promise<DetectResult> {
  const metrics = computeMetrics(text);
  const signals = computeSignals(text);
  const raw = await openaiChat(
    DETECT_SYSTEM,
    detectPrompt(text, locale, metrics, signals),
    true,
    2000
  );
  const { score, sentences } = parseDetectJson(raw, text);
  return {
    score,
    verdict: verdictFromScore(score),
    confidence: "medium",
    sentences,
    metrics,
    engine: "openai",
  };
}

async function geminiDetect(text: string, locale: string): Promise<DetectResult> {
  const metrics = computeMetrics(text);
  const signals = computeSignals(text);
  const raw = await geminiChat(
    DETECT_SYSTEM,
    detectPrompt(text, locale, metrics, signals),
    true,
    2000
  );
  const { score, sentences } = parseDetectJson(raw, text);
  return {
    score,
    verdict: verdictFromScore(score),
    confidence: "medium",
    sentences,
    metrics,
    engine: "gemini",
  };
}

/**
 * Honest confidence: short texts carry weak signal, and disagreement
 * between the statistical and LLM engines means the case is genuinely
 * ambiguous. Competitors hide this; we surface it.
 */
function confidenceFor(wordCount: number, engineGap: number | null): Confidence {
  let level: Confidence = wordCount < 40 ? "low" : wordCount < 100 ? "medium" : "high";
  if (engineGap !== null && engineGap > 30 && level !== "low") {
    level = level === "high" ? "medium" : "low";
  }
  if (engineGap === null && level === "high") level = "medium"; // single engine caps at medium
  return level;
}

function wordsOf(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

/** Split long text into ~maxWords chunks at sentence boundaries. */
function chunkText(text: string, maxWords = 600): string[] {
  const sentences = splitSentences(text);
  const chunks: string[] = [];
  let current: string[] = [];
  let count = 0;
  for (const s of sentences) {
    const w = s.split(/\s+/).length;
    if (count + w > maxWords && current.length > 0) {
      chunks.push(current.join(" "));
      current = [];
      count = 0;
    }
    current.push(s);
    count += w;
  }
  if (current.length > 0) chunks.push(current.join(" "));
  return chunks;
}

async function llmDetect(
  text: string,
  locale: string,
  provider: Exclude<Provider, "heuristic">
): Promise<DetectResult> {
  if (provider === "gemini") return geminiDetect(text, locale);
  if (provider === "openai") return openaiDetect(text, locale);
  return claudeDetect(text, locale);
}

/** One hybrid pass over a single chunk. */
async function detectChunk(
  text: string,
  locale: string,
  provider: Exclude<Provider, "heuristic">
): Promise<{ score: number; gap: number; sentences: Sentence[]; words: number }> {
  const statistical = heuristicDetect(text);
  const llm = await llmDetect(text, locale, provider);
  const blended = Math.round(llm.score * 0.65 + statistical.score * 0.35);
  return {
    score: blended,
    gap: Math.abs(llm.score - statistical.score),
    sentences: llm.sentences,
    words: wordsOf(text),
  };
}

/** The statistical result for one chunk, shaped like a model result. */
function statisticalChunk(text: string) {
  const s = heuristicDetect(text);
  return { score: s.score, gap: 0, sentences: s.sentences, words: wordsOf(text), llm: false };
}

/**
 * Hybrid ensemble: model judgment blended with the deterministic signals
 * (65/35), with those signals also fed into the prompt as evidence. Long texts
 * are chunked at sentence boundaries and merged by word-weighted average, so
 * per-sentence quality holds up at Ultimate-plan lengths.
 *
 * Chunks run one at a time, and a chunk that fails falls back to its own
 * statistical score instead of taking the whole analysis down with it.
 *
 * Both of those exist for the free tier. Firing five chunks at once is the
 * fastest way to spend a free key's per-minute allowance on a single paste,
 * and the previous all-or-nothing Promise.all meant one rate-limited chunk
 * discarded four good model reads. Sequential is slower per request and far
 * more likely to return a model-quality answer at all.
 */
export async function detectAI(text: string, locale: string): Promise<DetectResult> {
  const provider = pickProvider();
  const statistical = heuristicDetect(text);
  const words = wordsOf(text);

  if (provider === "heuristic") {
    return { ...statistical, confidence: confidenceFor(words, null) };
  }

  const chunks = chunkText(text);
  const results: ReturnType<typeof statisticalChunk>[] = [];
  for (const chunk of chunks) {
    try {
      results.push({ ...(await detectChunk(chunk, locale, provider)), llm: true });
    } catch {
      results.push(statisticalChunk(chunk));
    }
  }

  const usedModel = results.filter((r) => r.llm);
  if (usedModel.length === 0) {
    // Every call failed — usually a rate limit or a missing key. Say so through
    // the engine field so the interface can warn instead of quietly showing a
    // degraded number as though it were the full analysis.
    return { ...statistical, confidence: confidenceFor(words, null) };
  }

  const totalWords = results.reduce((s, r) => s + r.words, 0) || 1;
  const score = Math.round(
    results.reduce((s, r) => s + r.score * r.words, 0) / totalWords
  );
  // Only chunks the model actually read can disagree with it.
  const maxGap = Math.max(...usedModel.map((r) => r.gap));

  return {
    score,
    verdict: verdictFromScore(score),
    confidence: confidenceFor(words, maxGap),
    sentences: results.flatMap((r) => r.sentences),
    metrics: statistical.metrics,
    engine: "hybrid",
  };
}

/* ------------------------------------------------------------------
   Humanizer
------------------------------------------------------------------ */
/**
 * Substitutions, kept deliberately aligned with what the detector counts.
 *
 * These two lists had drifted apart: the detector had learned a much larger
 * inventory of stock connectives, so the rewriter was leaving behind exactly
 * the phrases the score was punishing and the verify loop kept — correctly —
 * discarding its own output as no improvement. Anything added to STOCK_EN or
 * STOCK_AR in detector-stats needs a landing place here, or the humanizer
 * cannot fix what the detector complains about.
 *
 * Replacements are meaning-preserving on purpose. Swapping a connective for a
 * plainer connective is safe; swapping a hedge for a claim is not, so the
 * hedges left here are only the ones with an exact plain equivalent.
 */
function heuristicHumanize(text: string, isArabic: boolean): string {
  let out = text;
  const swaps: [RegExp, string][] = isArabic
    ? [
        [/علاوةً? على ذلك،?/g, "وأيضاً"],
        [/بالإضافة إلى ذلك،?/g, "وكذلك"],
        [/إضافةً? إلى ذلك،?/g, "وكذلك"],
        [/فضلاً عن ذلك،?/g, "وكذلك"],
        [/من الجدير بالذكر أنه?/g, "المهم أن"],
        [/تجدر الإشارة إلى أنه?/g, "لاحظ أن"],
        [/جدير بالذكر أنه?/g, "المهم أن"],
        [/(?:و)?في الختام،?/g, "وأخيراً"],
        [/في نهاية المطاف،?/g, "في النهاية"],
        [/(?:و)?من ناحية أخرى،?/g, "في المقابل"],
        [/على صعيد آخر،?/g, "في المقابل"],
        [/في هذا السياق،?/g, "وهنا"],
        [/في هذا الصدد،?/g, "وهنا"],
        [/مما لا شك فيه أنه?/g, "بلا شك"],
        [/لا يخفى على أحد أنه?/g, "معروف أن"],
        [/وبناءً? على ذلك،?/g, "لذلك"],
        [/(?:و)?بالتالي،?/g, "لذلك"],
        [/يمكن القول إنه?/g, "أي أن"],
        [/بشكل عام،?/g, "عموماً"],
        // Not "له دور": the phrase is usually followed by an accusative
        // adjective ("دوراً محورياً"), and swapping the verb for a possessive
        // left the adjective stranded in the wrong case — "له دور محورياً".
        // "يؤدي" carries the same meaning and the same grammar.
        [/يلعب دوراً/g, "يؤدي دوراً"],
        [/تلعب دوراً/g, "تؤدي دوراً"],
      ]
    : [
        // compound phrases first so they don't get double-replaced
        [/\bFurthermore, it is important to note that\b/gi, "And worth noting:"],
        [/\bMoreover, it is important to\b/gi, "It also matters to"],
        [/\bFurthermore,?\b/gi, "Also,"],
        [/\bMoreover,?\b/gi, "On top of that,"],
        [/\bAdditionally,?\b/gi, "Also,"],
        [/\bIn addition,?\b/gi, "Plus,"],
        [/\bIn conclusion,?\b/gi, "So, to wrap up,"],
        [/\bIn summary,?\b/gi, "To sum up,"],
        [/\bIt is important to note that\b/gi, "Worth mentioning:"],
        [/\bIt is (?:also )?worth noting that\b/gi, "note that"],
        [/\bIt should be noted that\b/gi, "note that"],
        [/\bIt is important to consider\b/gi, "Take a moment to consider"],
        [/\bIt is important to\b/gi, "It matters to"],
        [/\bIn today'?s world,?\b/gi, "These days,"],
        [/\bin the ever-evolving\b/gi, "in the fast-moving"],
        [/\bOn the other hand,?\b/gi, "By contrast,"],
        [/\bAs a result,?\b/gi, "So,"],
        [/\bConsequently,?\b/gi, "So,"],
        [/\bUltimately,?\b/gi, "In the end,"],
        [/\bAt the end of the day,?\b/gi, "In the end,"],
        [/\bOverall,?\b/gi, "On the whole,"],
        [/\bIn essence,?\b/gi, "Basically,"],
        [/\bIn other words,?\b/gi, "Put differently,"],
        [/\bThat being said,?\b/gi, "Still,"],
        [/\bLast but not least,?\b/gi, "Finally,"],
        [/\bwhen it comes to\b/gi, "with"],
        [/\ba testament to\b/gi, "proof of"],
        [/\bin the realm of\b/gi, "in"],
        [/\bnavigating the\b/gi, "handling the"],
        [/\bunderscores\b/gi, "shows"],
        [/\bplays a crucial role\b/gi, "really matters"],
        [/\bdelve into\b/gi, "dig into"],
        [/\bseamless\b/gi, "smooth"],
        [/\bholistic\b/gi, "well-rounded"],
        [/\brobust\b/gi, "solid"],
        [/\bleverage\b/gi, "use"],
        [/\butilize\b/gi, "use"],
        [/\bfacilitate\b/gi, "help"],
        [/\bnumerous\b/gi, "many"],
      ];
  for (const [re, rep] of swaps) out = out.replace(re, rep);
  // soften semicolons
  out = out.replace(/;\s+/g, isArabic ? "، و" : ". ");
  // cleanup: collapse doubled punctuation/spaces left by swaps
  out = out
    // A swap beginning with "و" landing after an existing "و" leaves "وو",
    // which reads as a typo rather than as prose.
    .replace(/(^|[\s،,])وو/g, "$1و")
    .replace(/،\s*،/g, "،")
    .replace(/,\s*,/g, ",")
    .replace(/\s+([,.،])/g, "$1")
    .replace(/([,.])\s*([,.])/g, "$1")
    .replace(/\s{2,}/g, " ")
    .trim();

  // Rhythm surgery: raise burstiness by splitting long sentences at a
  // mid-comma and merging consecutive short ones. This is what actually
  // moves machine-uniform text toward human unevenness.
  const sentences = splitSentences(out);
  if (sentences.length >= 2) {
    const lens = sentences.map((s) => s.split(/\s+/).length);
    const mean = lens.reduce((a, b) => a + b, 0) / lens.length;
    const variance =
      lens.reduce((a, b) => a + (b - mean) ** 2, 0) / lens.length;
    const cv = mean > 0 ? Math.sqrt(variance) / mean : 0;
    const veryUniform = cv < 0.35; // machine-flat rhythm: force alternation
    const comma = isArabic ? "،" : ",";
    const rebuilt: string[] = [];
    let i = 0;
    while (i < sentences.length) {
      const s = sentences[i];
      const len = lens[i];
      const next = sentences[i + 1];
      const nextLen = lens[i + 1] ?? 0;

      if (len > mean * 1.3 && s.includes(comma + " ")) {
        // split near the middle comma
        const parts = s.split(comma + " ");
        let acc = parts[0];
        let k = 1;
        while (k < parts.length - 1 && acc.length < s.length / 2) {
          acc += comma + " " + parts[k];
          k++;
        }
        const rest = parts.slice(k).join(comma + " ");
        // Both halves have to be able to stand as sentences. Splitting after a
        // leading connective produced fragments like "On top of that." — a
        // burstier rhythm bought with a sentence that isn't one.
        const MIN_HALF_WORDS = 5;
        const viable =
          rest.trim() &&
          acc.split(/\s+/).filter(Boolean).length >= MIN_HALF_WORDS &&
          rest.split(/\s+/).filter(Boolean).length >= MIN_HALF_WORDS;
        if (viable) {
          const first = /[.!?؟]$/.test(acc) ? acc : acc + ".";
          const second = rest.charAt(0).toUpperCase() + rest.slice(1);
          rebuilt.push(first, isArabic ? rest : second);
          i++;
          continue;
        }
      }

      const mergeable =
        next !== undefined &&
        ((len < mean * 0.75 && nextLen < mean * 0.75) ||
          // flat machine rhythm: force a merge on alternating pairs
          (veryUniform && i % 3 === 1 && len + nextLen < mean * 2.6));
      if (mergeable) {
        const head = s.replace(/[.!?؟]$/, "");
        const tail = isArabic ? next : next.charAt(0).toLowerCase() + next.slice(1);
        rebuilt.push(`${head}${isArabic ? "، و" : ", and "}${tail}`);
        i += 2;
        continue;
      }

      rebuilt.push(s);
      i++;
    }
    out = rebuilt.join(" ");
  }

  // Swaps are written lower-case so they read correctly mid-sentence; this
  // puts the capital back wherever one actually starts a sentence.
  if (!isArabic) {
    out = out.replace(/(^|[.!?]\s+)([a-z])/g, (_, lead, letter) => lead + letter.toUpperCase());
  }

  // Repeated last, because the merge above joins clauses with "، و" and the
  // clause it joins on often already begins with one — which is how a rewrite
  // that had been cleaned of doubled waws grew a fresh "ووأخيراً" on the way out.
  if (isArabic) out = out.replace(/(^|[\s،,])وو/g, "$1و");

  return out.trim();
}

const STYLE_INSTRUCTIONS: Record<HumanizeStyle, string> = {
  natural:
    "Target register: the author's own natural voice — balanced, neither formal nor slangy.",
  academic:
    "Target register: polished academic prose — precise, measured, formal, but still with human rhythm variety. For Arabic: فصحى رصينة بأسلوب أكاديمي متزن.",
  casual:
    "Target register: relaxed, conversational, approachable — contractions and light phrasing welcome. For Arabic: فصحى مبسّطة قريبة من القارئ دون عامية مبتذلة.",
};

function humanizeSystem(locale: string, style: HumanizeStyle): string {
  return `You are "Sahihly"'s humanizer. Rewrite AI-sounding text so it reads as natural human writing while preserving the EXACT original meaning, facts, and language (${locale}). Vary sentence length and rhythm, remove robotic transitions and repetition. ${STYLE_INSTRUCTIONS[style]} For Arabic, produce fluent, grammatically correct Modern Standard Arabic. Do NOT add facts, do NOT translate, do NOT add commentary. Output ONLY the rewritten text.`;
}

async function openaiHumanize(
  text: string,
  locale: string,
  style: HumanizeStyle
): Promise<string> {
  const out = await openaiChat(humanizeSystem(locale, style), text, false, 4000);
  return out.trim() || text;
}

async function claudeHumanize(
  text: string,
  locale: string,
  style: HumanizeStyle
): Promise<string> {
  const anthropic = getAnthropic();
  const sys = humanizeSystem(locale, style);
  const msg = await anthropic.messages.create({
    model: MODEL,
    max_tokens: 4000,
    system: sys,
    messages: [{ role: "user", content: text }],
  });
  const raw = msg.content.find((c) => c.type === "text");
  return raw && "text" in raw ? raw.text.trim() : text;
}

async function geminiHumanize(
  text: string,
  locale: string,
  style: HumanizeStyle
): Promise<string> {
  const out = await geminiChat(humanizeSystem(locale, style), text, false, 4000);
  return out.trim() || text;
}

/**
 * Did the rewrite keep the substance?
 *
 * Only long words count. A humanizer is supposed to replace "furthermore" with
 * "also" and "leverage" with "use" — that is the entire job — so a plain
 * bag-of-words comparison punishes it for succeeding. What must survive is the
 * material that carries the argument: names, technical terms, numbers, the
 * specific nouns a paraphrase has no business dropping.
 */
function contentOverlap(before: string, after: string): number {
  const bag = (t: string) =>
    new Set(
      t
        .toLowerCase()
        .replace(/[^\p{L}\p{N}\s]/gu, " ")
        .split(/\s+/)
        .filter((w) => w.length >= 6 || /\d/.test(w))
    );
  const a = bag(before);
  const b = bag(after);
  if (a.size === 0) return 1;
  let kept = 0;
  for (const w of a) if (b.has(w)) kept++;
  return kept / a.size;
}

/**
 * Rewrite, then check the rewrite.
 *
 * A single pass is a guess: the model is asked to sound human and has no idea
 * whether it succeeded, so it sometimes returns prose that is flatter than
 * what it was given. Scoring the output against the same engine that scores
 * the input turns that guess into a measurement, and one retry is enough to
 * catch most of it.
 *
 * The overlap guard exists for the opposite failure. Told to vary the rhythm,
 * a model will occasionally start dropping clauses, and a humanizer that
 * quietly deletes a third of someone's argument is worse than one that does
 * nothing. If too little of the original vocabulary survives, the rewrite is
 * discarded rather than shown — losing the improvement is recoverable, losing
 * the meaning is not.
 */
const MIN_CONTENT_KEPT = 0.6;

export async function humanizeText(
  text: string,
  locale: string,
  style: HumanizeStyle = "natural"
): Promise<HumanizeResult> {
  const isArabic = isArabicText(text);
  const provider = pickProvider();
  const before = styleSignalScore(text);

  const rewrite = (input: string) => {
    if (provider === "gemini") return geminiHumanize(input, locale, style);
    if (provider === "openai") return openaiHumanize(input, locale, style);
    return claudeHumanize(input, locale, style);
  };

  if (provider !== "heuristic") {
    try {
      let best = await rewrite(text);
      let bestScore = styleSignalScore(best);

      // Only retry when the first pass actually failed to help. A second call
      // costs the user latency, so it has to be earning something.
      if (bestScore >= before) {
        const second = await rewrite(text);
        if (styleSignalScore(second) < bestScore) {
          best = second;
          bestScore = styleSignalScore(second);
        }
      }

      if (contentOverlap(text, best) >= MIN_CONTENT_KEPT) {
        const engine: Engine =
          provider === "gemini" ? "gemini" : provider === "openai" ? "openai" : "claude";
        return { text: best, engine };
      }
    } catch {
      /* fall through to heuristic */
    }
  }

  // No overlap guard on this path. The deterministic rewriter is a closed set
  // of substitutions plus sentence splitting and merging — it cannot delete a
  // claim, only rephrase one — so the only question worth asking is whether it
  // helped. Its sentence surgery is blunt enough to sometimes make things
  // worse, and when it does, the original is the better answer.
  const local = heuristicHumanize(text, isArabic);
  return { text: styleSignalScore(local) < before ? local : text, engine: "heuristic" };
}
