import type { Metadata } from "next";
import Link from "next/link";
import { isLocale, type Locale, SITE_URL } from "@/lib/i18n/config";
import Reveal from "@/components/Reveal";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const loc: Locale = isLocale(locale) ? locale : "en";
  return {
    title:
      loc === "ar"
        ? "قاموس مصطلحات كشف الذكاء الاصطناعي"
        : "AI Detection Glossary — Every Term Explained",
    description:
      loc === "ar"
        ? "شرح مبسّط لكل مصطلحات كشف الذكاء الاصطناعي: الحيرة، التباين، ثراء المفردات، التنسين، وأكثر — بالعربية والإنجليزية."
        : "Plain-language definitions of every AI-detection term: perplexity, burstiness, lexical diversity, humanizing, and more — in English and Arabic.",
    alternates: { canonical: "/glossary" },
  };
}

type Term = { id: string; term: Record<Locale, string>; def: Record<Locale, string> };

const TERMS: Term[] = [
  {
    id: "ai-detector",
    term: { en: "AI Detector", ar: "كاشف الذكاء الاصطناعي" },
    def: {
      en: "A tool that estimates how likely a text was generated by a language model, based on statistical and stylistic signals. Output is a probability, never a certainty.",
      ar: "أداة تقدّر احتمال أن نصاً ما وُلِّد بنموذج لغوي، اعتماداً على إشارات إحصائية وأسلوبية. الناتج احتمال، وليس يقيناً أبداً.",
    },
  },
  {
    id: "ai-humanizer",
    term: { en: "AI Humanizer", ar: "مُنسّن النصوص" },
    def: {
      en: "A tool that rewrites machine-sounding text into a natural human voice — varying rhythm and removing robotic patterns — while preserving the original meaning.",
      ar: "أداة تعيد صياغة النص الآلي بصوت بشري طبيعي — بتنويع الإيقاع وإزالة الأنماط الروبوتية — مع الحفاظ على المعنى الأصلي.",
    },
  },
  {
    id: "perplexity",
    term: { en: "Perplexity", ar: "الحيرة (Perplexity)" },
    def: {
      en: "A measure of how surprised a language model is by each next word. Human writing tends to have higher perplexity (more surprising word choices) than machine writing.",
      ar: "مقياس لمدى مفاجأة النموذج اللغوي بكل كلمة تالية. الكتابة البشرية عادةً أعلى حيرةً (اختيارات كلمات أكثر مفاجأة) من كتابة الآلة.",
    },
  },
  {
    id: "burstiness",
    term: { en: "Burstiness", ar: "التباين (Burstiness)" },
    def: {
      en: "How much sentence length and complexity vary across a passage. Humans naturally alternate short and long sentences; AI text is often suspiciously uniform.",
      ar: "مدى تنوّع طول الجمل وتعقيدها عبر النص. البشر يناوبون طبيعياً بين جمل قصيرة وطويلة؛ بينما نص الآلة غالباً منتظم بشكل مريب.",
    },
  },
  {
    id: "lexical-diversity",
    term: { en: "Lexical Diversity", ar: "ثراء المفردات" },
    def: {
      en: "The ratio of unique words to total words (type-token ratio). Low diversity — the same words recycled again and again — is a common machine-writing signal.",
      ar: "نسبة الكلمات الفريدة إلى إجمالي الكلمات. الثراء المنخفض — تدوير الكلمات نفسها مراراً — إشارة شائعة على الكتابة الآلية.",
    },
  },
  {
    id: "ai-tells",
    term: { en: "AI Tells", ar: "العلامات الآلية" },
    def: {
      en: "Stock phrases that language models overuse: \"furthermore\", \"in today's world\", \"it is important to note\". A high density of tells raises AI-likelihood scores.",
      ar: "عبارات جاهزة تفرط النماذج اللغوية في استخدامها: «علاوة على ذلك»، «في عالم اليوم»، «من الجدير بالذكر». كثافتها العالية ترفع نتيجة احتمال الذكاء الاصطناعي.",
    },
  },
  {
    id: "false-positive",
    term: { en: "False Positive", ar: "الإيجابي الكاذب" },
    def: {
      en: "When a detector flags genuinely human writing as AI-generated. The most damaging kind of detector error — and the reason scores must never be treated as proof.",
      ar: "حين يَسِم الكاشف كتابةً بشرية أصيلة بأنها آلية. أخطر أنواع أخطاء الكواشف — والسبب في وجوب عدم اعتبار النتائج دليلاً قاطعاً.",
    },
  },
  {
    id: "llm",
    term: { en: "LLM (Large Language Model)", ar: "النموذج اللغوي الكبير (LLM)" },
    def: {
      en: "The technology behind ChatGPT, Claude, and Gemini: a neural network trained on vast text to predict the next word, which lets it generate fluent language.",
      ar: "التقنية خلف ChatGPT وClaude وGemini: شبكة عصبية دُرّبت على نصوص هائلة لتوقّع الكلمة التالية، ما يمكّنها من توليد لغة سلسة.",
    },
  },
  {
    id: "register",
    term: { en: "Register", ar: "المستوى اللغوي (Register)" },
    def: {
      en: "The formality level of writing — academic, professional, casual. Good humanizing keeps meaning while shifting register; in Arabic this spans فصحى رصينة to فصحى مبسّطة.",
      ar: "درجة رسمية الكتابة — أكاديمية، مهنية، أو مبسّطة. التنسين الجيد يحفظ المعنى مع ضبط المستوى؛ وفي العربية يمتد من الفصحى الرصينة إلى الفصحى المبسّطة.",
    },
  },
  {
    id: "academic-integrity",
    term: { en: "Academic Integrity", ar: "النزاهة الأكاديمية" },
    def: {
      en: "The ethical rules of scholarship: submitting your own work and disclosing assistance when required. Style tools must be used within your institution's policies.",
      ar: "قواعد البحث الأخلاقية: تقديم عملك أنت والإفصاح عن المساعدة حين تُطلب. يجب استخدام أدوات الأسلوب ضمن سياسات مؤسستك.",
    },
  },
];

export default async function GlossaryPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale: raw } = await params;
  const locale: Locale = isLocale(raw) ? raw : "en";

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "DefinedTermSet",
    name: locale === "ar" ? "قاموس مصطلحات كشف الذكاء الاصطناعي" : "AI Detection Glossary",
    url: `${SITE_URL}/glossary`,
    hasDefinedTerm: TERMS.map((t) => ({
      "@type": "DefinedTerm",
      "@id": `${SITE_URL}/glossary#${t.id}`,
      name: t.term[locale],
      description: t.def[locale],
    })),
  };

  return (
    <div className="container-x max-w-3xl py-16">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <Reveal>
        <h1 className="text-center text-4xl font-bold sm:text-5xl">
          {locale === "ar" ? "قاموس المصطلحات" : "AI Detection Glossary"}
        </h1>
        <p className="mx-auto mt-3 max-w-2xl text-center text-white/60">
          {locale === "ar"
            ? "كل مصطلح تصادفه في عالم كشف الذكاء الاصطناعي — مشروحاً ببساطة."
            : "Every term you'll meet in the AI-detection world — explained simply."}
        </p>
      </Reveal>

      <div className="mt-12 space-y-4">
        {TERMS.map((t, i) => (
          <Reveal key={t.id} delay={Math.min(i, 5)} as="div">
            <div id={t.id} className="glass scroll-mt-24 rounded-2xl p-6">
              <h2 className="text-lg font-semibold text-violet-200">{t.term[locale]}</h2>
              <p className="mt-2 text-sm leading-relaxed text-white/60">{t.def[locale]}</p>
            </div>
          </Reveal>
        ))}
      </div>

      <Reveal>
        <div className="mt-12 rounded-2xl border border-violet-400/20 bg-violet-400/[0.05] p-6 text-center">
          <Link href="/ai-detector" className="font-medium text-violet-300 hover:text-violet-200">
            {locale === "ar"
              ? "شاهد هذه المفاهيم عملياً — جرّب الكاشف مجاناً"
              : "See these concepts in action — try the detector free"}
          </Link>
        </div>
      </Reveal>
    </div>
  );
}
