import type { Locale } from "@/lib/i18n/config";

export type Term = {
  id: string;
  term: Record<Locale, string>;
  /** One-line definition, also used for the DefinedTerm schema. */
  def: Record<Locale, string>;
  /** The part a one-liner cannot carry: why the idea matters, where it
   *  misleads people, and how it behaves differently in Arabic. */
  long: Record<Locale, string>;
};

export const TERMS: Term[] = [
  {
    id: "ai-detector",
    term: { en: "AI Detector", ar: "كاشف الذكاء الاصطناعي" },
    def: {
      en: "A tool that estimates how likely a text was generated by a language model, based on statistical and stylistic signals. Output is a probability, never a certainty.",
      ar: "أداة تقدّر احتمال أن نصاً ما وُلِّد بنموذج لغوي، اعتماداً على إشارات إحصائية وأسلوبية. الناتج احتمال، وليس يقيناً أبداً.",
    },
    long: {
      en: "Detectors do not recognise text as machine-written the way antivirus recognises a known file. There is no watermark and no registry of everything a model has produced. What they measure is predictability, which means honest writing that happens to be smooth and conventional lands in the same statistical space as generated text. This is why every serious detector reports a probability, why confidence should drop sharply on short passages, and why a score cannot support an accusation on its own.",
      ar: "لا تتعرّف الكواشف على النص الآلي كما يتعرّف مضاد الفيروسات على ملف معروف. فلا علامة مائية ولا سجلّ لكل ما أنتجه نموذج. وما تقيسه هو قابلية التوقّع، ما يعني أن كتابة نزيهة تصادف أن تكون سلسة وتقليدية تقع في المساحة الإحصائية نفسها للنص المولّد. ولهذا يعرض كل كاشف جادّ احتمالاً، ولهذا ينبغي أن تهبط الثقة بحدّة في المقاطع القصيرة، ولهذا لا تكفي النتيجة وحدها لدعم اتهام.",
    },
  },
  {
    id: "ai-humanizer",
    term: { en: "AI Humanizer", ar: "مُنسّن النصوص" },
    def: {
      en: "A tool that rewrites machine-sounding text into a natural human voice — varying rhythm and removing robotic patterns — while preserving the original meaning.",
      ar: "أداة تعيد صياغة النص الآلي بصوت بشري طبيعي — بتنويع الإيقاع وإزالة الأنماط الروبوتية — مع الحفاظ على المعنى الأصلي.",
    },
    long: {
      en: "The useful distinction is between a humanizer and a paraphraser. A paraphraser swaps vocabulary, which is exactly what breaks technical writing — a synonym that is close enough in general prose can be wrong in a clinical or legal sentence. A humanizer works on structure instead: sentence-length variance, opening constructions, and the connective filler models overuse. Because it leaves terminology alone, meaning survives. Used honestly it makes your own writing sound like you; used to disguise authorship from an integrity check it is misconduct at most institutions.",
      ar: "التمييز المفيد بين المُنسّن وأداة إعادة الصياغة. فأداة إعادة الصياغة تستبدل المفردات، وهو تحديداً ما يُفسد الكتابة التقنية — فالمرادف القريب بما يكفي في النثر العام قد يكون خاطئاً في جملة سريرية أو قانونية. أما المُنسّن فيعمل على البنية: تباين أطوال الجمل وتراكيب الافتتاح وحشو الربط الذي تُفرط النماذج فيه. ولأنه يترك المصطلحات، ينجو المعنى. واستخدامه بأمانة يجعل كتابتك تبدو بصوتك؛ واستخدامه لتمويه التأليف أمام فحص نزاهة مخالفةٌ في معظم المؤسسات.",
    },
  },
  {
    id: "perplexity",
    term: { en: "Perplexity", ar: "الحيرة (Perplexity)" },
    def: {
      en: "A measure of how surprised a language model is by each next word. Human writing tends to have higher perplexity (more surprising word choices) than machine writing.",
      ar: "مقياس لمدى مفاجأة النموذج اللغوي بكل كلمة تالية. الكتابة البشرية عادةً أعلى حيرةً (اختيارات كلمات أكثر مفاجأة) من كتابة الآلة.",
    },
    long: {
      en: "Think of it as the model's running surprise. At each word the model has expectations; when your next word is one it would have predicted, perplexity is low. Machine text sits low because that is literally how it was produced — by choosing likely continuations. The trap is assuming low perplexity means machine authorship. Formal registers, standardised academic formats, and writing in a second language all produce predictable word choices for entirely human reasons, which is a large part of why false positives cluster where they do.",
      ar: "تخيّلها مفاجأة النموذج المستمرة. فعند كل كلمة تكون لديه توقّعات؛ وحين تأتي كلمتك التالية مما كان سيتوقّعه تنخفض الحيرة. ونصّ الآلة منخفض لأن هذه حرفياً طريقة إنتاجه — باختيار التكملات المرجّحة. والفخّ هو افتراض أن انخفاض الحيرة يعني تأليفاً آلياً. فالمستويات الرسمية والقوالب الأكاديمية المعيارية والكتابة بلغة ثانية كلها تُنتج اختيارات متوقّعة لأسباب بشرية تماماً، وهذا جزء كبير من سبب تجمّع الأخطاء حيث تتجمّع.",
    },
  },
  {
    id: "burstiness",
    term: { en: "Burstiness", ar: "التباين (Burstiness)" },
    def: {
      en: "How much sentence length and complexity vary across a passage. Humans naturally alternate short and long sentences; AI text is often suspiciously uniform.",
      ar: "مدى تنوّع طول الجمل وتعقيدها عبر النص. البشر يناوبون طبيعياً بين جمل قصيرة وطويلة؛ بينما نص الآلة غالباً منتظم بشكل مريب.",
    },
    long: {
      en: "Human writing is uneven in a way that is hard to fake and hard to suppress. A short declarative lands, then a long qualifying clause unspools, then a fragment. Models trained to produce fluent text drift toward a comfortable middle length and stay there, so the variance flattens. Burstiness is usually the single most informative signal a detector has — and the fastest thing a writer can fix, because splitting one long sentence and merging two short ones changes it immediately.",
      ar: "الكتابة البشرية متفاوتة بطريقة يصعب تزييفها ويصعب كبتها. فجملة خبرية قصيرة تقع، ثم تنسدل عبارة تقييد طويلة، ثم شذرة. والنماذج المدرَّبة على إنتاج نصّ سلس تنجرف نحو طول أوسط مريح وتبقى فيه، فيستوي التباين. والتباين عادةً أكثر إشارة يملكها الكاشف إفادةً — وأسرع ما يستطيع الكاتب إصلاحه، لأن تقسيم جملة طويلة ودمج قصيرتين يغيّره فوراً.",
    },
  },
  {
    id: "lexical-diversity",
    term: { en: "Lexical Diversity", ar: "ثراء المفردات" },
    def: {
      en: "The ratio of unique words to total words (type-token ratio). Low diversity — the same words recycled again and again — is a common machine-writing signal.",
      ar: "نسبة الكلمات الفريدة إلى إجمالي الكلمات. الثراء المنخفض — تدوير الكلمات نفسها مراراً — إشارة شائعة على الكتابة الآلية.",
    },
    long: {
      en: "Measured as the ratio of distinct words to total words, it captures how much a passage repeats itself. Generated text often circles a narrow set of reliable words, while human writing reaches for the odd specific term. The measure is length-sensitive in a way people forget: any long text repeats more simply because common words recur, so comparing diversity across passages of very different lengths tells you little. It is also lower in Arabic for structural reasons rather than stylistic ones.",
      ar: "يُقاس بنسبة الكلمات المتمايزة إلى مجموع الكلمات، ويلتقط كم يكرّر المقطع نفسه. فالنص المولّد كثيراً ما يدور حول مجموعة ضيّقة من كلمات مضمونة، بينما تمدّ الكتابة البشرية يدها للمصطلح النادر المحدّد. والمقياس حسّاس للطول بشكل ينساه الناس: فأي نصّ طويل يكرّر أكثر لمجرّد تكرار الكلمات الشائعة، ولذلك لا تخبرك مقارنة التنوّع بين مقاطع شديدة التفاوت في الطول بالكثير. وهو أيضاً أدنى في العربية لأسباب بنيوية لا أسلوبية.",
    },
  },
  {
    id: "ai-tells",
    term: { en: "AI Tells", ar: "العلامات الآلية" },
    def: {
      en: "Stock phrases that language models overuse: \"furthermore\", \"in today's world\", \"it is important to note\". A high density of tells raises AI-likelihood scores.",
      ar: "عبارات جاهزة تفرط النماذج اللغوية في استخدامها: «علاوة على ذلك»، «في عالم اليوم»، «من الجدير بالذكر». كثافتها العالية ترفع نتيجة احتمال الذكاء الاصطناعي.",
    },
    long: {
      en: "The recognisable verbal habits of generated prose: connective scaffolding such as furthermore and moreover, throat-clearing openers along the lines of it is important to note that, the reflexive three-part list, and closing paragraphs that announce a conclusion and then restate what was already said. None of these is wrong in isolation — human writers use all of them — but their density and predictability is the giveaway. They are also the easiest thing to fix in a draft, because deleting most of them costs nothing.",
      ar: "العادات اللفظية المميّزة للنثر المولّد: سقالات الربط مثل «علاوة على ذلك» و«بالإضافة إلى ذلك»، وتنحنح الافتتاح من نوع «من المهم الإشارة إلى أن»، والقوائم الثلاثية التلقائية، وفقرات الختام التي تُعلن خلاصة ثم تعيد ما قيل. ولا شيء من هذه خاطئ بمفرده — فالكاتبون البشر يستخدمونها جميعاً — لكن كثافتها وقابليتها للتوقّع هي ما يفضح. وهي أيضاً أسهل ما يُصلَح في مسودّة، لأن حذف معظمها لا يكلّف شيئاً.",
    },
  },
  {
    id: "false-positive",
    term: { en: "False Positive", ar: "الإيجابي الكاذب" },
    def: {
      en: "When a detector flags genuinely human writing as AI-generated. The most damaging kind of detector error — and the reason scores must never be treated as proof.",
      ar: "حين يَسِم الكاشف كتابةً بشرية أصيلة بأنها آلية. أخطر أنواع أخطاء الكواشف — والسبب في وجوب عدم اعتبار النتائج دليلاً قاطعاً.",
    },
    long: {
      en: "The failure mode that matters most, because it falls on people rather than on machines. Published research has found AI detectors flag essays by non-native English writers at dramatically higher rates than native speakers, and the same structural bias appears whenever a model calibrated on one language judges another. Rigid academic formats, careful editing, and systematic writing styles all push honest prose toward the statistical territory of generated text. This is the reason a detection score must never be the sole basis for an academic or employment decision.",
      ar: "نمط الفشل الأهمّ، لأنه يقع على الناس لا على الآلات. فقد وجدت أبحاث منشورة أن كواشف الذكاء الاصطناعي تُصنِّف مقالات غير الناطقين بالإنجليزية كآلية بمعدلات أعلى بكثير من الناطقين الأصليين، والانحياز البنيوي نفسه يظهر كلما حكم نموذج مُعايَر على لغة على لغة أخرى. والقوالب الأكاديمية الصارمة والتحرير الدقيق وأساليب الكتابة المنهجية كلها تدفع النثر النزيه نحو المنطقة الإحصائية للنص المولّد. وهذا سبب ألا تكون نتيجة الكشف أبداً الأساس الوحيد لقرار أكاديمي أو وظيفي.",
    },
  },
  {
    id: "llm",
    term: { en: "LLM (Large Language Model)", ar: "النموذج اللغوي الكبير (LLM)" },
    def: {
      en: "The technology behind ChatGPT, Claude, and Gemini: a neural network trained on vast text to predict the next word, which lets it generate fluent language.",
      ar: "التقنية خلف ChatGPT وClaude وGemini: شبكة عصبية دُرّبت على نصوص هائلة لتوقّع الكلمة التالية، ما يمكّنها من توليد لغة سلسة.",
    },
    long: {
      en: "A model trained to predict the next token across an enormous amount of text, which turns out to be enough to produce fluent prose, code, and translation. Two consequences matter for everything else in this glossary. First, its output is by construction statistically likely — which is exactly what detectors look for. Second, it has no notion of truth: fluent, confident, entirely fabricated citations are a normal failure mode, not a rare bug, which is why every reference a model gives you needs checking against the source.",
      ar: "نموذج مدرَّب على توقّع الرمز التالي عبر كمّ هائل من النصوص، ويتّضح أن هذا يكفي لإنتاج نثر سلس وشيفرة وترجمة. ولهذا نتيجتان تهمّان كل ما سواه في هذا القاموس. الأولى أن مخرجاته مرجّحة إحصائياً بحكم البناء — وهو تحديداً ما تبحث عنه الكواشف. والثانية أنه لا يملك مفهوماً للصدق: فالاستشهادات السلسة الواثقة المختلقة تماماً نمط فشل طبيعي لا خلل نادر، ولهذا يحتاج كل مرجع يعطيك إياه نموذج إلى تحقّق أمام المصدر.",
    },
  },
  {
    id: "register",
    term: { en: "Register", ar: "المستوى اللغوي (Register)" },
    def: {
      en: "The formality level of writing — academic, professional, casual. Good humanizing keeps meaning while shifting register; in Arabic this spans فصحى رصينة to فصحى مبسّطة.",
      ar: "درجة رسمية الكتابة — أكاديمية، مهنية، أو مبسّطة. التنسين الجيد يحفظ المعنى مع ضبط المستوى؛ وفي العربية يمتد من الفصحى الرصينة إلى الفصحى المبسّطة.",
    },
    long: {
      en: "The level of formality and the conventions that go with it — the difference between a lab report, a legal summary, a news article, and a message to a friend. Register matters here because detectors do not adjust for it. A methods section is supposed to be uniform and impersonal, so it reads as machine-like by construction. In Arabic the effect is stronger still, because the gap between Modern Standard Arabic and everyday speech is wider than the equivalent gap in English.",
      ar: "مستوى الرسمية والأعراف التي تصحبه — الفرق بين تقرير مخبري وملخّص قانوني ومقال إخباري ورسالة إلى صديق. والمستوى يهمّ هنا لأن الكواشف لا تُعدّل له. فقسم المنهجية يُفترض أن يكون منتظماً ولا شخصياً، فيُقرأ آلياً بحكم بنائه. وفي العربية الأثر أقوى، لأن الفجوة بين الفصحى والكلام اليومي أوسع من نظيرتها في الإنجليزية.",
    },
  },
  {
    id: "academic-integrity",
    term: { en: "Academic Integrity", ar: "النزاهة الأكاديمية" },
    def: {
      en: "The ethical rules of scholarship: submitting your own work and disclosing assistance when required. Style tools must be used within your institution's policies.",
      ar: "قواعد البحث الأخلاقية: تقديم عملك أنت والإفصاح عن المساعدة حين تُطلب. يجب استخدام أدوات الأسلوب ضمن سياسات مؤسستك.",
    },
    long: {
      en: "The set of rules an institution applies to authorship, citation, and permitted assistance — and they vary enormously. Some departments allow AI for brainstorming and editing but not drafting; others ban it for assessed work entirely; many now require a disclosure statement. Two things hold almost everywhere: undeclared use causes far more trouble than declared use, and a detector score is not evidence. If you are accused, your version history and drafts are stronger proof of authorship than any tool's opinion.",
      ar: "مجموعة القواعد التي تطبّقها المؤسسة على التأليف والاستشهاد والاستعانة المسموحة — وهي تتفاوت بشدّة. فبعض الأقسام يسمح بالذكاء الاصطناعي للعصف الذهني والتحرير دون الصياغة؛ وبعضها يمنعه كلياً في الأعمال المُقيَّمة؛ وكثير منها يشترط الآن بيان إفصاح. ويصحّ أمران في كل مكان تقريباً: الاستخدام غير المُعلن يسبّب متاعب أكثر بكثير من المُعلن، ونتيجة الكاشف ليست دليلاً. وإن اتُّهمت، فسجلّ نسخك ومسودّاتك أقوى إثباتاً للتأليف من رأي أي أداة.",
    },
  },
];
